version: '3.0'
services:
  strasbourgjs-website:
    container_name: 'strasbourgjs-website'
    build:
      context: './'
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
      - '/app/node_modules'
      - '/app/.nuxt'
